Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Settlers of Catan", price: 3499, released_at: "2011-07-15")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Seafarers of Catan", price: 3499, released_at: "2011-07-15")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "DVD Player", price: 7999, released_at: "2011-07-18")
Product.create!(category: Category.find_or_create_by_name("Clothing"), name: "Red Shirt", price: 1249)
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Black Leather Couch", price: 39999)
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Oak Coffee Table", price: 22399, released_at: "2011-07-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Technodrome", price: 2799, released_at: "2011-07-28")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Oh's Cereal", price: 395)
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Game Console", price: 29995, released_at: "2011-08-02")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Video Game", price: 2995, released_at: "2011-08-05")
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Lawn Chair", price: 3499, released_at: "2011-08-05")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "RailsCasts Pro Subscription", price: 900, released_at: "2011-10-03")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Dog Toy Bone", price: 299, released_at: "2011-08-08")
Product.create!(category: Category.find_or_create_by_name("Furniture"), name: "Heated Blanket", price: 2795, released_at: "2011-08-09")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "Flux Capacitor", price: 1955, released_at: "2011-08-12")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Plutonium", price: 239725, released_at: "2011-08-18")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Chocolate Pie", price: 314, released_at: "2011-03-14")
Product.create!(category: Category.find_or_create_by_name("Food"), name: "Ryan's Cheesecake", price: 4999, released_at: "2011-08-22")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Acoustic Guitar", price: 102500, released_at: "2011-08-23")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Model Enterprise", price: 2799, released_at: "2011-08-27")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Agricola", price: 4599, released_at: "2011-08-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Stone Age", price: 3499, released_at: "2011-08-30")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "7 Wonders", price: 2875)
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Millennium Falcon", price: 3597281, released_at: "2011-09-07")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Answer to Everything", price: 4200, released_at: "2011-09-08")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Box Kite", price: 6300, released_at: "2011-09-10")
Product.create!(category: Category.find_or_create_by_name("Misc"), name: "Phil's Painting", price: 39900, released_at: "2011-09-14")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "1000 Piece Jigsaw Puzzle", price: 1499, released_at: "2011-09-17")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "TextMate 2", price: 7500, released_at: "2011-09-22")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Bowling Ball", price: 12700, released_at: "2011-09-23")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Rubber Ducky", price: 475, released_at: "2011-09-25")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Unicorn Action Figure", price: 875, released_at: "2011-09-25")
Product.create!(category: Category.find_or_create_by_name("Hardware"), name: "Rack", price: 3249, released_at: "2011-09-28")
Product.create!(category: Category.find_or_create_by_name("Toys & Games"), name: "Model Train Rails", price: 4500, released_at: "2011-10-01")
Product.create!(category: Category.find_or_create_by_name("Electronics"), name: "CanCan Music Record", price: 299, released_at: "2011-10-04") 

User.create!(email: "prova@example.com", password: "secret", password_confirmation: "secret")

Product.all.each do |p|
  p.description = "#{p.name} "*5
  p.save
end
